import type { PersonnelRequest } from "./types"

export const MOCK_REQUESTS: PersonnelRequest[] = [
  {
    id: "20240218",
    date: "18 Şubat",
    company: "Polen",
    projectGroup: "Sera Projeleri",
    project: "Antalya Domates Serası",
    jobType: "Sera İşçiliği",
    duration: "1 Hafta",
    numberOfPeople: 2,
    totalHours: 19.5,
    cost: 2850,
    status: "pending",
    hasHistory: true,
    notes: "Acil ihtiyaç, lütfen en kısa sürede değerlendiriniz.",
    startDate: "19.02.2024",
    endDate: "26.02.2024",
  },
  {
    id: "20240217",
    date: "17 Şubat",
    company: "Polen",
    projectGroup: "Sera Projeleri",
    project: "Antalya Domates Serası",
    jobType: "Sera İşçiliği",
    duration: "2 Hafta",
    numberOfPeople: 2,
    totalHours: 13.5,
    cost: 1950,
    status: "pending",
  },
  {
    id: "20240216",
    date: "16 Şubat",
    company: "Polen",
    projectGroup: "Sera Projeleri",
    project: "Antalya Domates Serası",
    jobType: "Sera İşçiliği",
    duration: "1 Hafta",
    numberOfPeople: 2,
    totalHours: 15,
    cost: 2250,
    status: "approved",
    hasHistory: true,
    notes: "Onaylandı, personel listesi ekte.",
  },
]

