import type { Teklif } from "./types"

export const MOCK_TEKLIFLER: Teklif[] = [
  {
    id: "teklif-001",
    teklifNo: "FT-2025-123456",
    firmaAdi: "ABC Teknoloji",
    firmaSehir: "İstanbul",
    teklifTarihi: "2024-01-15",
    gecerlilikTarihi: "2024-02-15",
    durum: "beklemede",
    sozlesmeTuru: "gecici_is_iliskisi",
    karOrani: 20,
    toplamMaliyet: 45000,
    currentRevision: 2,
    meslekKodlari: [
      {
        kod: "YG-001",
        meslek: "Yazılım Geliştirici",
        kisiSayisi: 2,
        birimMaliyet: 15000,
      },
      {
        kod: "YG-002",
        meslek: "Sistem Yöneticisi",
        kisiSayisi: 1,
        birimMaliyet: 12000,
      },
    ],
    ekHizmetler: [
      {
        id: "ek-001",
        hizmetAdi: "Personel Servisi",
        fiyat: 150,
        tip: "kisi_basi_gun",
        dahilMi: false,
        aciklama: "Kişi başı günlük servis ücreti",
      },
      {
        id: "ek-002",
        hizmetAdi: "Ring Servisi",
        fiyat: 3000,
        tip: "sabit",
        dahilMi: true,
        aciklama: "Aylık sabit ring servis ücreti (sefer başı)",
      },
      {
        id: "ek-003",
        hizmetAdi: "Yemek Kartı",
        fiyat: 200,
        tip: "sabit",
        dahilMi: false,
        aciklama: "Aylık sabit yemek kartı ücreti",
      },
    ],
    hazirlayan: "Ahmet Yılmaz",
    revisionHistory: [
      {
        id: "rev-001",
        revisionNumber: 1,
        date: "2024-01-20T10:15:30Z",
        karOrani: 22,
        toplamMaliyet: 48000,
        revizyonYapan: "Ahmet Yılmaz",
        notes: "Müşteri talebine istinaden kâr oranı %22'ye yükseltildi.",
      },
      {
        id: "rev-002",
        revisionNumber: 2,
        date: "2024-01-25T14:22:45Z",
        karOrani: 20,
        toplamMaliyet: 45000,
        revizyonYapan: "Mehmet Demir",
        notes: "Rekabet koşulları nedeniyle kâr oranı %20'ye düşürüldü.",
      },
    ],
  },
  {
    id: "teklif-002",
    teklifNo: "FT-2025-123457-r3",
    firmaAdi: "XYZ Holding",
    firmaSehir: "Ankara",
    teklifTarihi: "2024-01-20",
    gecerlilikTarihi: "2024-02-20",
    durum: "beklemede",
    sozlesmeTuru: "danismanlik",
    karOrani: 22,
    toplamMaliyet: 65000,
    projeBaslangicTarihi: "2024-03-01",
    projeBitisTarihi: "2024-06-01",
    meslekKodlari: [
      {
        kod: "DN-001",
        meslek: "İş Analisti",
        kisiSayisi: 2,
        birimMaliyet: 18000,
      },
      {
        kod: "DN-002",
        meslek: "Proje Yöneticisi",
        kisiSayisi: 1,
        birimMaliyet: 22000,
      },
    ],
    hazirlayan: "Zeynep Kaya",
    currentRevision: 3,
    revisionHistory: [
      {
        id: "rev-001",
        revisionNumber: 1,
        date: "2024-01-25T10:15:30Z",
        karOrani: 25,
        toplamMaliyet: 60000,
        revizyonYapan: "Zeynep Kaya",
        notes: "Müşteri talebine istinaden kâr oranı %25'e yükseltildi.",
      },
      {
        id: "rev-002",
        revisionNumber: 2,
        date: "2024-01-28T14:22:45Z",
        karOrani: 23,
        toplamMaliyet: 62500,
        revizyonYapan: "Ahmet Yılmaz",
        notes: "Rekabet koşulları nedeniyle kâr oranı %23'e düşürüldü. Ek hizmet bedelleri revize edildi.",
        ekHizmetler: [
          {
            id: "ek-003",
            hizmetAdi: "Eğitim Hizmeti",
            fiyat: 4500,
          },
          {
            id: "ek-004",
            hizmetAdi: "Ulaşım Desteği",
            fiyat: 2500,
          },
        ],
      },
      {
        id: "rev-003",
        revisionNumber: 3,
        date: "2024-02-05T09:30:15Z",
        karOrani: 22,
        toplamMaliyet: 65000,
        revizyonYapan: "Mehmet Demir",
        notes:
          "Müşteri ile yapılan görüşme sonrası proje kapsamı genişletildi. Kâr oranı %22'ye düşürüldü ancak toplam maliyet artırıldı.",
        ekHizmetler: [
          {
            id: "ek-003",
            hizmetAdi: "Eğitim Hizmeti",
            fiyat: 4500,
          },
          {
            id: "ek-004",
            hizmetAdi: "Ulaşım Desteği",
            fiyat: 2500,
          },
          {
            id: "ek-005",
            hizmetAdi: "Danışmanlık Paketi",
            fiyat: 8000,
          },
        ],
      },
    ],
  },
  {
    id: "teklif-003",
    teklifNo: "FT-2025-123458",
    firmaAdi: "123 Sanayi",
    firmaSehir: "İzmir",
    teklifTarihi: "2024-01-25",
    gecerlilikTarihi: "2024-02-25",
    durum: "beklemede",
    sozlesmeTuru: "gecici_is_iliskisi",
    karOrani: 18,
    toplamMaliyet: 35000,
    meslekKodlari: [
      {
        kod: "UR-001",
        meslek: "Üretim Operatörü",
        kisiSayisi: 5,
        birimMaliyet: 7000,
      },
    ],
    ekHizmetler: [
      {
        id: "ek-001",
        hizmetAdi: "Personel Servisi",
        fiyat: 150,
        tip: "kisi_basi_gun",
        dahilMi: false,
        aciklama: "Kişi başı günlük servis ücreti",
      },
      {
        id: "ek-002",
        hizmetAdi: "Ring Servisi",
        fiyat: 3000,
        tip: "sabit",
        dahilMi: true,
        aciklama: "Aylık sabit ring servis ücreti (sefer başı)",
      },
      {
        id: "ek-003",
        hizmetAdi: "Yemek Kartı",
        fiyat: 200,
        tip: "sabit",
        dahilMi: false,
        aciklama: "Aylık sabit yemek kartı ücreti",
      },
    ],
    hazirlayan: "Mehmet Demir",
  },
  {
    id: "teklif-red-001",
    teklifNo: "FT-2025-000789",
    firmaAdi: "Teknoloji A.Ş.",
    firmaSehir: "İzmir",
    teklifTarihi: "2024-02-15",
    gecerlilikTarihi: "2024-03-15",
    durum: "reddedildi",
    sozlesmeTuru: "gecici_is_iliskisi",
    karOrani: 18,
    redNedeni:
      "Maliyet çok yüksek, revizyon gerekli. Hizmet bedellerinde indirim yapılması ve ek hizmetlerin yeniden değerlendirilmesi talep ediliyor.",
    meslekKodlari: [
      {
        kod: "YG-003",
        meslek: "Veri Analisti",
        kisiSayisi: 2,
        birimMaliyet: 18500,
      },
      {
        kod: "YG-005",
        meslek: "UI/UX Tasarımcı",
        kisiSayisi: 1,
        birimMaliyet: 16000,
      },
    ],
    ekHizmetler: [
      {
        id: "ek-001",
        hizmetAdi: "Personel Servisi",
        fiyat: 150,
        tip: "kisi_basi_gun",
        dahilMi: false,
        aciklama: "Kişi başı günlük servis ücreti",
      },
      {
        id: "ek-002",
        hizmetAdi: "Ring Servisi",
        fiyat: 3000,
        tip: "sabit",
        dahilMi: true,
        aciklama: "Aylık sabit ring servis ücreti (sefer başı)",
      },
      {
        id: "ek-003",
        hizmetAdi: "Yemek Kartı",
        fiyat: 200,
        tip: "sabit",
        dahilMi: false,
        aciklama: "Aylık sabit yemek kartı ücreti",
      },
    ],
    hazirlayan: "Seda Sel",
    currentRevision: 1,
    revisionHistory: [
      {
        id: "rev-001",
        revisionNumber: 1,
        date: "2024-02-20T10:15:30Z",
        karOrani: 15,
        toplamMaliyet: 50000,
        revizyonYapan: "Seda Sel",
        notes: "Maliyet düşürüldü ancak müşteri yine de reddetti.",
      },
    ],
  },
  {
    id: "teklif-onay-001",
    teklifNo: "FT-2025-000123",
    firmaAdi: "Global Yazılım Ltd.",
    firmaSehir: "Ankara",
    teklifTarihi: "2024-01-10",
    gecerlilikTarihi: "2024-02-10",
    durum: "onaylandi",
    sozlesmeTuru: "danismanlik",
    karOrani: 21,
    toplamMaliyet: 78000,
    meslekKodlari: [
      {
        kod: "YG-010",
        meslek: "Senior Yazılım Geliştirici",
        kisiSayisi: 2,
        birimMaliyet: 25000,
      },
      {
        kod: "YG-011",
        meslek: "DevOps Uzmanı",
        kisiSayisi: 1,
        birimMaliyet: 28000,
      },
    ],
    ekHizmetler: [
      {
        id: "ek-001",
        hizmetAdi: "Personel Servisi",
        fiyat: 150,
        tip: "kisi_basi_gun",
        dahilMi: false,
        aciklama: "Kişi başı günlük servis ücreti",
      },
      {
        id: "ek-002",
        hizmetAdi: "Ring Servisi",
        fiyat: 3000,
        tip: "sabit",
        dahilMi: true,
        aciklama: "Aylık sabit ring servis ücreti (sefer başı)",
      },
      {
        id: "ek-003",
        hizmetAdi: "Yemek Kartı",
        fiyat: 200,
        tip: "sabit",
        dahilMi: false,
        aciklama: "Aylık sabit yemek kartı ücreti",
      },
    ],
    hazirlayan: "Ali Yıldız",
    currentRevision: 2,
    revisionHistory: [
      {
        id: "rev-001",
        revisionNumber: 1,
        date: "2024-01-15T09:30:00Z",
        karOrani: 23,
        toplamMaliyet: 82000,
        revizyonYapan: "Ali Yıldız",
        notes: "İlk teklife göre kapsam genişletildi.",
      },
      {
        id: "rev-002",
        revisionNumber: 2,
        date: "2024-01-20T14:45:00Z",
        karOrani: 21,
        toplamMaliyet: 78000,
        revizyonYapan: "Mehmet Demir",
        notes: "Müşteri talebi üzerine fiyat düşürüldü ve bu haliyle onaylandı.",
      },
    ],
  },
]

