import type { DailyTimesheet } from "./types"

export const REJECTION_REASONS = ["Fazla mesai onaylanmadı", "Yanlış saat girişi", "İş tamamlanmadı", "Diğer"]

export const LABOR_TYPES = [
  "Sera İşçiliği",
  "Sulama İşçiliği",
  "İnşaat İşçiliği",
  "Elektrik İşçiliği",
  "Mekanik İşçiliği",
  "Montaj İşçiliği",
  "Temizlik İşçiliği",
  "Diğer",
]

export const SAMPLE_DATA: DailyTimesheet[] = [
  {
    id: "20240218",
    date: "18 Şubat 2024",
    company: "Polen",
    entries: [
      {
        id: "20240218-1",
        employeeName: "Ahmet Yılmaz",
        tckn: "12345678901",
        laborType: "Sera İşçiliği",
        overtimeHours: 9.5, // Normal mesai 8 saat, 1.5 saat fazla mesai
        wage: 150,
        cost: 1425,
        startTime: "08:00",
        endTime: "17:30",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Yılmaz Tarım Ltd. Şti.",
      },
      {
        id: "20240218-2",
        employeeName: "Mehmet Demir",
        tckn: "12345678902",
        laborType: "Sera İşçiliği",
        overtimeHours: 9.5,
        wage: 150,
        cost: 1425,
        startTime: "08:00",
        endTime: "17:30",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Yılmaz Tarım Ltd. Şti.",
      },
    ],
    totalEmployees: 2,
    totalOvertimeHours: 19,
    totalCost: 2850,
    extraOvertimeHours: 3, // 1.5 saat x 2 kişi = 3 saat fazla mesai
  },
  {
    id: "20240217",
    date: "17 Şubat 2024",
    company: "Polen",
    entries: [
      {
        id: "20240217-1",
        employeeName: "Ayşe Kaya",
        tckn: "12345678903",
        laborType: "Sera İşçiliği",
        overtimeHours: 6.5, // Normal mesai 8 saat, 1.5 saat eksik mesai
        wage: 150,
        cost: 975,
        startTime: "08:00",
        endTime: "14:30",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Demir Tarım Ltd. Şti.",
      },
      {
        id: "20240217-2",
        employeeName: "Ali Yıldız",
        tckn: "12345678904",
        laborType: "Sera İşçiliği",
        overtimeHours: 6.5,
        wage: 150,
        cost: 975,
        startTime: "08:00",
        endTime: "14:30",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Demir Tarım Ltd. Şti.",
      },
    ],
    totalEmployees: 2,
    totalOvertimeHours: 13,
    totalCost: 1950,
    missingHours: 3, // 1.5 saat x 2 kişi = 3 saat eksik mesai
  },
  {
    id: "20240216",
    date: "16 Şubat 2024",
    company: "Polen",
    entries: [
      {
        id: "20240216-1",
        employeeName: "Ahmet Yılmaz",
        tckn: "12345678901",
        laborType: "Sera İşçiliği",
        overtimeHours: 7.5,
        wage: 150,
        cost: 1125,
        startTime: "17:00",
        endTime: "00:30",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Yılmaz Tarım Ltd. Şti.",
      },
      {
        id: "20240216-2",
        employeeName: "Mehmet Demir",
        tckn: "12345678902",
        laborType: "Sera İşçiliği",
        overtimeHours: 7.5,
        wage: 150,
        cost: 1125,
        startTime: "17:00",
        endTime: "00:30",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Yılmaz Tarım Ltd. Şti.",
      },
    ],
    totalEmployees: 2,
    totalOvertimeHours: 15,
    totalCost: 2250,
  },
  {
    id: "20240215",
    date: "15 Şubat 2024",
    company: "Polen",
    entries: [
      {
        id: "20240215-1",
        employeeName: "Ahmet Yılmaz",
        tckn: "12345678901",
        laborType: "Hasat İşçiliği",
        overtimeHours: 7.5,
        wage: 150,
        cost: 1125,
        startTime: "17:00",
        endTime: "00:30",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Yılmaz Tarım Ltd. Şti.",
      },
      {
        id: "20240215-2",
        employeeName: "Mehmet Demir",
        tckn: "12345678902",
        laborType: "Hasat İşçiliği",
        overtimeHours: 7.5,
        wage: 150,
        cost: 1125,
        startTime: "17:00",
        endTime: "00:30",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Yılmaz Tarım Ltd. Şti.",
      },
      {
        id: "20240215-3",
        employeeName: "Ayşe Kaya",
        tckn: "12345678903",
        laborType: "Hasat İşçiliği",
        overtimeHours: 7.5,
        wage: 150,
        cost: 1125,
        startTime: "17:00",
        endTime: "00:30",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Demir Tarım Ltd. Şti.",
      },
    ],
    totalEmployees: 3,
    totalOvertimeHours: 22.5,
    totalCost: 3375,
  },
  {
    id: "20240214",
    date: "14 Şubat 2024",
    company: "Polen",
    entries: [
      {
        id: "20240214-1",
        employeeName: "Ahmet Yılmaz",
        tckn: "12345678901",
        laborType: "Sulama İşçiliği",
        overtimeHours: 5,
        wage: 150,
        cost: 750,
        startTime: "17:00",
        endTime: "22:00",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Yılmaz Tarım Ltd. Şti.",
        missingHours: 1.5,
      },
      {
        id: "20240214-2",
        employeeName: "Mehmet Demir",
        tckn: "12345678902",
        laborType: "Sulama İşçiliği",
        overtimeHours: 5,
        wage: 150,
        cost: 750,
        startTime: "17:00",
        endTime: "22:00",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Yılmaz Tarım Ltd. Şti.",
        missingHours: 1.5,
      },
    ],
    totalEmployees: 2,
    totalOvertimeHours: 10,
    totalCost: 1500,
    missingHours: 3, // Added total missing hours (1.5 × 2)
  },
  {
    id: "20240213",
    date: "13 Şubat 2024",
    company: "Polen",
    entries: [
      {
        id: "20240213-1",
        employeeName: "Ayşe Kaya",
        tckn: "12345678903",
        laborType: "İlaçlama İşçiliği",
        overtimeHours: 6,
        wage: 150,
        cost: 900,
        startTime: "17:00",
        endTime: "23:00",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Demir Tarım Ltd. Şti.",
        extraOvertimeHours: 2.5, // Updated value
      },
      {
        id: "20240213-2",
        employeeName: "Mehmet Demir",
        tckn: "12345678902",
        laborType: "İlaçlama İşçiliği",
        overtimeHours: 6,
        wage: 150,
        cost: 900,
        startTime: "17:00",
        endTime: "23:00",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Demir Tarım Ltd. Şti.",
        extraOvertimeHours: 2,
      },
      {
        id: "20240213-3",
        employeeName: "Ali Yıldız",
        tckn: "12345678904",
        laborType: "İlaçlama İşçiliği",
        overtimeHours: 6,
        wage: 150,
        cost: 900,
        startTime: "17:00",
        endTime: "23:00",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Demir Tarım Ltd. Şti.",
        extraOvertimeHours: 2,
      },
    ],
    totalEmployees: 3,
    totalOvertimeHours: 18,
    totalCost: 2700,
    extraOvertimeHours: 6,
  },
  {
    id: "20240212",
    date: "12 Şubat 2024",
    company: "Polen",
    entries: [
      {
        id: "20240212-1",
        employeeName: "Fatma Şahin",
        tckn: "12345678905",
        laborType: "Sera İşçiliği",
        overtimeHours: 6, // Normal mesai 8 saat, 2 saat eksik
        wage: 150,
        cost: 900,
        startTime: "09:00",
        endTime: "15:00",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Yılmaz Tarım Ltd. Şti.",
        missingHours: 2,
      },
      {
        id: "20240212-2",
        employeeName: "Mustafa Yılmaz",
        tckn: "12345678906",
        laborType: "Sera İşçiliği",
        overtimeHours: 6, // Normal mesai 8 saat, 2 saat eksik
        wage: 150,
        cost: 900,
        startTime: "09:00",
        endTime: "15:00",
        company: "Polen",
        projectGroup: "Sera Projeleri",
        project: "Antalya Domates Serası",
        subcontractor: "Yılmaz Tarım Ltd. Şti.",
        missingHours: 2,
      },
    ],
    totalEmployees: 2,
    totalOvertimeHours: 12,
    totalCost: 1800,
    missingHours: 4,
  },
]

